let auth = localStorage.getItem("nix_admin_token") || "";
const $=id=>document.getElementById(id);
async function api(url,opts={}){opts.headers={...(opts.headers||{}),Authorization:`Bearer ${auth}`,"Content-Type":"application/json"};const r=await fetch(url,opts);const d=await r.json().catch(()=>({error:"Resposta inválida"}));if(!r.ok)throw new Error(d.detail||d.error||`HTTP ${r.status}`);return d}
function showApp(){ $("login").hidden=true;$("app").hidden=false; tokenStatus(); }
async function login(){try{const r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("loginPass").value})});const d=await r.json();if(!r.ok)throw Error(d.error);auth=d.token;localStorage.setItem("nix_admin_token",auth);showApp()}catch(e){$("loginMsg").textContent=e.message;$("loginMsg").className="err"}}
function logout(){localStorage.removeItem("nix_admin_token");location.reload()}
async function tokenStatus(){try{const d=await api("/api/token/status");$("tokenStatus").textContent=d.configured?"Token configurado ✓":"Token ainda não configurado";$("tokenStatus").className=d.configured?"ok":"err"}catch{}}
async function saveToken(){try{await api("/api/token",{method:"POST",body:JSON.stringify({token:$("apiToken").value})});$("apiToken").value="";tokenStatus();alert("Token salvo com segurança no backend.")}catch(e){alert(e.message)}}
function modeChanged(){const br=$("mode").value==="br_padrao";$("brFields").hidden=!br;$("delay").max=br?20:10;if(!br&&+$("delay").value>10)$("delay").value=10}
async function createRoom(){try{const mode=$("mode").value;const body={password:$("roomPass").value,start_delay_minutes:+$("delay").value,config_type:mode,room_name:$("roomName").value,map_name:$("map").value};if(mode==="br_padrao"){body.equipe=$("team").value;body.espectadores=+$("spec").value}const d=await api("/api/rooms",{method:"POST",body:JSON.stringify(body)});$("session").value=d.session_id;$("createOut").textContent=JSON.stringify(d,null,2);$("roomInfo").innerHTML=`<p><b>Sala:</b> ${esc(d.room_name||"")}<br><b>Room ID:</b> ${esc(d.room_id)}<br><b>Convite:</b> ${esc(d.invite_code||"")}<br><a target="_blank" rel="noopener" href="${escAttr(d.invite_link||"#")}">Abrir convite</a></p>`}catch(e){$("createOut").textContent=e.message}}
function sid(){if(!$("session").value)throw Error("Informe a Session ID");return encodeURIComponent($("session").value)}
async function loadMembers(){try{const d=await api(`/api/rooms/${sid()}/members?include_loadout=true`);$("members").innerHTML=(d.members||[]).map(m=>`<div class="member"><span><b>${esc(m.nickname)}</b><br>UID: ${esc(m.player_uid)} · Time ${esc(m.team)} · ${esc(m.platform)}</span><button onclick="kick('${escAttr(m.player_uid)}')">Expulsar</button></div>`).join("")||"<p>Nenhum jogador.</p>"}catch(e){$("members").textContent=e.message}}
async function kick(uid){if(!confirm("Expulsar este jogador?"))return;try{await api(`/api/rooms/${sid()}/kick`,{method:"POST",body:JSON.stringify({player_uid:uid})});loadMembers()}catch(e){alert(e.message)}}
async function startRoom(){try{$("resultOut").textContent=JSON.stringify(await api(`/api/rooms/${sid()}/start`,{method:"POST"}),null,2)}catch(e){$("resultOut").textContent=e.message}}
async function result(){try{$("resultOut").textContent=JSON.stringify(await api(`/api/rooms/${sid()}/result`),null,2)}catch(e){$("resultOut").textContent=e.message}}
async function releaseRoom(){if(!confirm("Encerrar a sala e liberar a sessão?"))return;try{$("resultOut").textContent=JSON.stringify(await api(`/api/rooms/${sid()}/release`,{method:"POST"}),null,2)}catch(e){$("resultOut").textContent=e.message}}
async function balance(){try{$("balanceOut").textContent=JSON.stringify(await api("/api/balance"),null,2)}catch(e){$("balanceOut").textContent=e.message}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function escAttr(v){return esc(v)}
if(auth)showApp(); modeChanged();